fsoso_web/fsoso_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('web/', include('web.urls')),
    path('admin/', admin.site.urls),
]

fsoso_web/web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('resources', views.resources, name='resources'),
    path('resources/<int:resource_id>', views.resource, name='resource'),
    path('needs', views.needs, name='needs'),
    path('needs/<int:need_id>', views.need, name='need'),
]

fsoso_web/web/models.py
from django.utils import timezone
from django.db import models
from django.db.models import Q


class Good(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    expires_at = models.DateTimeField('expires at', blank=True, null=True)
    # TODO type, location, amount

    def __str__(self):
        return self.name

    def is_expired(self):
        return self.expires_at < timezone.now()

    @classmethod
    def non_expired(cls):
        return cls.objects.filter(Q(expires_at__gte=timezone.now()) | Q(expires_at=None))

class Resource(Good):
    condition = models.TextField(blank=True, null=True)
    consumed = models.BooleanField()

class Need(Good):
    fulfilled = models.BooleanField()

fsoso_web/web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import Resource, Need

def index(request):
    resources = Resource.non_expired()[:10]
    needs = Need.non_expired()[:10]
    context = {
        'resources': resources,
        'needs': needs,
    }
    return render(request, 'web/index.html', context)

def resources(request):
    resources = Resource.non_expired()
    context = {
        'resources': resources,
    }
    return render(request, 'web/resources.html', context)

def resource(request, resource_id):
    resource = Resource.objects.get(pk=resource_id)
    context = {
        'resource': resource,
    }
    return render(request, 'web/resource.html', context)

def needs(request):
    needs = Need.non_expired()
    context = {
        'needs': needs,
    }
    return render(request, 'web/needs.html', context)

def need(request, need_id):
    need = Resource.objects.get(pk=need_id)
    context = {
        'need': need,
    }
    return render(request, 'web/need.html', context)

fsoso_web/web/templates/web/index.html
<h3>Resources and Needs</h3>

<div class="resources">
    {% if resources %}
        <ul>
        {% for resource in resources %}
            <li><a href={% url 'web:resource' resource.id %}>{{ resource.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Resources are available.</p>
    {% endif %}
    <a href={% url 'web:resources' %}>More Resources</a>
</div>

<div class="needs">
    {% if needs %}
        <ul>
        {% for need in needs %}
        <li><a href={% url 'web:need' need.id %}>{{ need.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Needs were communicated.</p>
    {% endif %}
    <a href={% url 'web:needs' %}>More Needs</a>
</div>

fsoso_web/web/templates/web/need.html
<a href={% url 'web:index' %}>Home</a>

<p>{{need.name}}</p>
<p>{{need.description}}</p>
<p>{{need.expires_at}}</p>
<p>{{need.fulfilled}}</p>

fsoso_web/web/templates/web/needs.html
<h3>Needs</h3>

<a href={% url 'web:index' %}>Home</a>

<div class="needs">
    {% if needs %}
        <ul>
        {% for need in needs %}
            <li><a href={% url 'web:need' need.id %}>{{ need.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Needs were communicated.</p>
    {% endif %}
</div>

fsoso_web/web/templates/web/resource.html
<a href={% url 'web:index' %}>Home</a>

<p>{{resource.name}}</p>
<p>{{resource.description}}</p>
<p>{{resource.expires_at}}</p>
<p>{{resource.consumed}}</p>
<p>{{resource.condition}}</p>

fsoso_web/web/templates/web/resources.html
<h3>Resources</h3>

<a href={% url 'web:index' %}>Home</a>

<div class="resources">
    {% if resources %}
        <ul>
        {% for resource in resources %}
            <li><a href={% url 'web:resource' resource.id %}>{{ resource.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Resources are available.</p>
    {% endif %}
</div>